server {
    listen 80;

    # Sirve la app OHIF
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy hacia Orthanc — resuelve el nombre de servicio Docker internamente
    # El browser pide a localhost:3001/orthanc/* → nginx reenvía a orthanc:8042/*
    location /orthanc/ {
        proxy_pass         http://orthanc:8042/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_http_version 1.1;

        # Permite respuestas DICOM grandes
        proxy_read_timeout  300;
        proxy_send_timeout  300;
        client_max_body_size 500m;

        # Añade CORS para que OHIF pueda consumir los datos
        add_header Access-Control-Allow-Origin  *  always;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
        add_header Access-Control-Allow-Headers "*" always;
        if ($request_method = OPTIONS) {
            return 204;
        }
    }
}
